#!/usr/bin/env python3
"""Scan academic prose for authorial-voice and generic AI-style risks.

This is a writing-quality helper, not an AI detector.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "audit-reports" / "authorial-voice"
EVENT_LOG = ROOT / "research-wiki" / "SESSION_EVENT_LOG.jsonl"


@dataclass
class Finding:
    severity: str
    category: str
    line: int
    evidence: str
    action: str


CONNECTIVE_PATTERNS: list[tuple[str, str]] = [
    (r"\bthis\s+(?:distinction\s+)?matters\s+because\b", "repeated connective template"),
    (r"\btaken\s+together\b", "repeated connective template"),
    (r"\btogether,\s+these\b", "repeated connective template"),
    (r"\bthese\s+(?:sources|studies)\s+(?:show|suggest|support|provide|indicate)\b", "source-aggregation template"),
    (r"\b(?:this|these)\s+\w+\s+(?:helps?|support|supports|frames|specif(?:y|ies)|structure|structures)\b", "formulaic warrant connector"),
    (r"\bis\s+useful\s+(?:for|because)\b", "formulaic usefulness warrant"),
]

LEXEME_CAPS: list[tuple[str, str, int]] = [
    (r"\bconditions?\b", "overused framing lexeme", 8),
    (r"\bsensiti[sz](?:e|es|ed|ing)\b", "overused framing lexeme", 5),
    (r"\bbounded\b", "overused framing lexeme", 5),
    (r"\bcautious(?:ly)?\b", "overused framing lexeme", 5),
    (r"\bdeliberate(?:ly)?\b", "overused framing lexeme", 5),
]

CODA_PATTERNS: list[tuple[str, str]] = [
    (r"\bteacher\s+interviews?\b", "repeated methodology coda"),
    (r"\binterview\s+evidence\b", "repeated methodology coda"),
    (r"\bteachers'? own reasoning should still determine\b", "repeated methodology coda"),
    (r"\bconcept\s+card\b", "repeated methodology coda"),
    (r"\bthis\s+(?:project|study|dissertation|thesis|article|report)\b", "repeated project self-reference coda"),
]


PATTERNS: list[tuple[str, str, str, str]] = [
    (
        r"\b(lower|reduce|bypass|evade).{0,45}\b(AI|AIGC|Turnitin|GPTZero|detector|detection).{0,20}\b(rate|score|detector|detection|detectability|flag)\b",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"\b(lower|reduce|bypass|evade).{0,35}\b(AI|AIGC).{0,12}\b(detection|detector)\b",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"(降低|减少|规避|绕过).{0,12}(AI|AIGC|检测|检测率|查重|Turnitin|GPTZero)",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"(降\s*AI|AI\s*率|去\s*AI\s*味|AI\s*痕迹|论文降\s*AI|降低\s*AIGC)",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"\b(randomi[sz]e|synonym[- ]swap|insert.{0,20}(noise|imperfection)|evade.{0,20}pattern)\b",
        "HOLD",
        "style-evasion tactic",
        "Do not use randomisation, synonym swapping, or deliberate imperfections as an evasion tactic.",
    ),
    (
        r"(随机化|同义词替换|插入噪声|制造不完美|规避模式)",
        "HOLD",
        "style-evasion tactic",
        "Do not use randomisation, synonym swapping, or deliberate imperfections as an evasion tactic.",
    ),
    (
        r"\b(hide|omit|avoid|soften).{0,30}(AI[- ]use|AI disclosure|disclosure statement)\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\b(leave out|don'?t include|do not include|no need to mention).{0,30}\b(AI|AI statement|AI[- ]use|AI disclosure|disclosure statement)\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\bleave.{0,20}\b(AI|AI statement|AI[- ]use|AI disclosure|disclosure statement).{0,12}\bout\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"(隐藏|省略|不写|不要写|淡化).{0,12}(AI使用|AI声明|AI披露|人工智能使用|披露)",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\b(as an ai|as a language model|i am an ai|i'?m an ai|generated by ai)\b",
        "HOLD",
        "prompt or chatbot residue",
        "Remove chatbot meta-text before academic use.",
    ),
    (
        r"\b(it is important to note|it is worth noting|in today'?s.*landscape|rapidly evolving|delve into|shed light on|plays a crucial role)\b",
        "WARN",
        "generic AI-style phrasing",
        "Replace with a direct claim, specific mechanism, or delete the phrase.",
    ),
    (
        r"\b(crucial|pivotal|paramount|multifaceted|nuanced|robust|comprehensive|holistic|seamless|transformative)\b",
        "WARN",
        "inflated or vague academic vocabulary",
        "Quantify, specify, or remove the adjective.",
    ),
    (
        r"\b(furthermore|moreover|additionally)\b",
        "WARN",
        "formulaic transition",
        "Use a transition that states the paragraph's argumentative job.",
    ),
    (
        r"\b(proves|confirms|ensures|eliminates|conclusively demonstrates)\b",
        "WARN",
        "possible overclaim",
        "Check source strength; hedge unless evidence directly supports the certainty.",
    ),
    (
        r"^\s*(This|These|That)\s+(shows|suggests|indicates|means|allows|enables)\b",
        "WARN",
        "weak demonstrative opening",
        "Name the antecedent or rewrite the sentence as a specific mini-claim.",
    ),
]


def resolve(path_text: str) -> Path:
    path = Path(path_text).expanduser()
    return path if path.is_absolute() else ROOT / path


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path.resolve())


def scan(text: str) -> list[Finding]:
    findings: list[Finding] = []
    in_fence = False
    for index, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        quoted_or_fenced = in_fence or stripped.startswith(">")
        for pattern, severity, category, action in PATTERNS:
            if quoted_or_fenced and severity == "WARN":
                continue
            if re.search(pattern, line, flags=re.I):
                findings.append(
                    Finding(
                        severity=severity,
                        category=category,
                        line=index,
                        evidence=line.strip()[:220],
                        action=action,
                    )
                )
    findings.extend(scan_document_patterns(text))
    return findings


def body_lines(text: str) -> list[tuple[int, str]]:
    lines: list[tuple[int, str]] = []
    in_fence = False
    in_frontmatter = False
    seen_nonblank = False
    in_references = False
    previous_nonblank = ""
    for index, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if index == 1 and stripped == "---":
            in_frontmatter = True
            continue
        if in_frontmatter:
            if stripped == "---":
                in_frontmatter = False
            continue
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or stripped.startswith(">"):
            continue
        if re.match(r"^(#+\s*)?(references|bibliography|reference list|works cited|参考文献)\s*$", stripped, flags=re.I):
            in_references = True
            continue
        if re.match(r"^-{3,}$", stripped) and re.match(r"^(references|bibliography|reference list|works cited|参考文献)$", previous_nonblank, flags=re.I):
            in_references = True
            continue
        if in_references:
            continue
        if stripped:
            seen_nonblank = True
            previous_nonblank = stripped
        if seen_nonblank:
            lines.append((index, line))
    return lines


def paragraph_blocks(text: str) -> list[tuple[int, str]]:
    blocks: list[tuple[int, str]] = []
    current: list[str] = []
    start_line = 0
    for line_no, line in body_lines(text):
        stripped = line.strip()
        if not stripped:
            if current:
                blocks.append((start_line, " ".join(current).strip()))
                current = []
                start_line = 0
            continue
        if stripped.startswith("#"):
            if current:
                blocks.append((start_line, " ".join(current).strip()))
                current = []
                start_line = 0
            continue
        if not current:
            start_line = line_no
        current.append(stripped)
    if current:
        blocks.append((start_line, " ".join(current).strip()))
    return blocks


def sentences(text: str) -> list[tuple[int, str]]:
    results: list[tuple[int, str]] = []
    for line_no, paragraph in paragraph_blocks(text):
        for sentence in re.split(r"(?<=[.!?])\s+", paragraph):
            sentence = sentence.strip()
            if sentence:
                results.append((line_no, sentence))
    return results


def add_doc_finding(findings: list[Finding], category: str, evidence: str, action: str, severity: str = "WARN") -> None:
    findings.append(
        Finding(
            severity=severity,
            category=category,
            line=0,
            evidence=evidence[:220],
            action=action,
        )
    )


def scan_document_patterns(text: str) -> list[Finding]:
    findings: list[Finding] = []
    body = "\n".join(line for _, line in body_lines(text))
    lowered = body.lower()

    for pattern, category in CONNECTIVE_PATTERNS:
        matches = re.findall(pattern, lowered, flags=re.I)
        if len(matches) > 1:
            add_doc_finding(
                findings,
                category,
                f"`{pattern}` occurs {len(matches)} times.",
                "Replace repeated template connectors with specific logic labels: cause, contrast, limitation, application, or synthesis.",
            )

    for pattern, category, cap in LEXEME_CAPS:
        matches = re.findall(pattern, lowered, flags=re.I)
        if len(matches) > cap:
            add_doc_finding(
                findings,
                category,
                f"`{pattern}` occurs {len(matches)} times; cap is {cap}.",
                "Check whether one framing term is carrying too much work; replace only where a more precise term clarifies the argument.",
            )

    paragraph_codas: list[str] = []
    final_token_grams: dict[str, int] = {}
    for _, paragraph in paragraph_blocks(text):
        parts = [part.strip() for part in re.split(r"(?<=[.!?])\s+", paragraph) if part.strip()]
        if not parts:
            continue
        final_sentence = parts[-1]
        lowered_final = final_sentence.lower()
        for pattern, category in CODA_PATTERNS:
            if re.search(pattern, lowered_final, flags=re.I):
                paragraph_codas.append(category)
                break
        tokens = re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", lowered_final)
        tail = tokens[-8:]
        for i in range(0, max(0, len(tail) - 3)):
            gram = " ".join(tail[i : i + 4])
            if gram:
                final_token_grams[gram] = final_token_grams.get(gram, 0) + 1
    repeated_codas = len(paragraph_codas)
    if repeated_codas > 1:
        add_doc_finding(
            findings,
            "repeated methodology or project coda",
            f"{repeated_codas} paragraph endings reuse methodology/project-positioning codas.",
            "Keep one strategic methodology coda per section; let other paragraphs end on the substantive literature judgement.",
        )
    repeated_tail = [gram for gram, count in final_token_grams.items() if count > 1]
    if repeated_tail:
        add_doc_finding(
            findings,
            "repeated paragraph-final phrase",
            f"Repeated final 4-gram(s): {', '.join(repeated_tail[:5])}.",
            "Vary paragraph endings by ending on a source distinction, limitation, or author judgement rather than the same coda.",
        )

    list_like_sentences = []
    abstract_list_terms = r"(?:conditions?|concerns?|risks?|support|trust|autonomy|workload|identity|governance|accountability|transparency|clarity|judgement|participation|confidence|integrity|privacy|uncertainty|training|policy|time|agency)"
    for line_no, sentence in sentences(text):
        lower_sentence = sentence.lower()
        comma_count = sentence.count(",")
        if comma_count >= 2 and re.search(r"\b(?:and|or)\s+" + abstract_list_terms + r"\b", lower_sentence):
            list_like_sentences.append((line_no, sentence))
    if len(list_like_sentences) >= 4:
        add_doc_finding(
            findings,
            "repeated abstract-noun list rhythm",
            f"{len(list_like_sentences)} sentences use 3+ item abstract-noun list endings.",
            "Keep lists only where they define a construct; otherwise convert the list into one controlling idea plus one concrete example.",
        )

    opener_hits = []
    for line_no, paragraph in paragraph_blocks(text):
        first = re.split(r"(?<=[.!?])\s+", paragraph.strip())[0]
        if re.search(r"\b(shows?|suggests?|helps?|supports?|frames?|identif(?:y|ies)|argues?|provides?|adds?|sharpens?)\b", first, flags=re.I):
            opener_hits.append((line_no, first[:120]))
    if len(opener_hits) >= 5:
        add_doc_finding(
            findings,
            "repeated paragraph-opener pattern",
            f"{len(opener_hits)} paragraphs open with source/function verbs such as shows, helps, supports, frames, or identifies.",
            "Vary paragraph openings: start some paragraphs with the author's judgement, the tension between sources, or the practical implication.",
        )

    short_authorial_sentences_by_section = 0
    for _, sentence in sentences(text):
        words = re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", sentence)
        has_abstract_list = sentence.count(",") >= 2 and re.search(r"\b(?:and|or)\b", sentence)
        is_meta = re.search(r"\b(this dissertation|this chapter|this study|interview evidence|teacher interviews?)\b", sentence, flags=re.I)
        if 0 < len(words) < 15 and not has_abstract_list and not is_meta:
            short_authorial_sentences_by_section += 1
    if short_authorial_sentences_by_section < 4 and len(paragraph_blocks(text)) >= 10:
        add_doc_finding(
            findings,
            "low short-sentence voice variance",
            f"Only {short_authorial_sentences_by_section} short non-meta sentences found.",
            "Add occasional short authorial judgement sentences where they clarify a source distinction or design choice.",
        )

    return findings


def status(findings: list[Finding]) -> str:
    if any(item.severity == "HOLD" for item in findings):
        return "HOLD"
    if findings:
        return "WARN"
    return "PASS"


def render(target: Path, findings: list[Finding]) -> str:
    result = status(findings)
    lines = [
        "# Authorial Voice Scan",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"Target: `{rel(target)}`",
        f"Status: `{result}`",
        "",
        "## Findings",
        "",
        "| Severity | Category | Line | Evidence | Action |",
        "|---|---|---:|---|---|",
    ]
    if findings:
        for item in findings:
            evidence = item.evidence.replace("|", "\\|")
            action = item.action.replace("|", "\\|")
            lines.append(f"| {item.severity} | {item.category} | {item.line} | {evidence} | {action} |")
    else:
        lines.append("| PASS | no finding | - | - | - |")
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This scan flags authorial-voice and generic AI-style risks. A `HOLD` result is a local workflow warning, not a judgement that text is AI-generated. This scan is not an AI detector, plagiarism detector, source-support check, or official university policy.",
            "",
        ]
    )
    return "\n".join(lines)


def append_event(target: Path, report: Path, result: str) -> None:
    EVENT_LOG.parent.mkdir(parents=True, exist_ok=True)
    categories = {finding.category for finding in scan(target.read_text(encoding="utf-8", errors="replace"))}
    skill = "academic-integrity-preflight" if {
        "AI-use disclosure risk",
        "prompt or chatbot residue",
    } & categories else "uk-academic-writing-style"
    event = {
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "run_id": f"authorial-voice-scan-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "window": "Maintenance",
        "event_type": "quality_gate",
        "status": "completed",
        "result": result,
        "skill": skill,
        "file": rel(report),
        "evidence": f"Authorial voice scan completed with result {result} for {rel(target)}.",
        "risk": "low" if result == "PASS" else "medium",
    }
    with EVENT_LOG.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(event, ensure_ascii=False) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run an authorial voice and generic AI-style scan.")
    parser.add_argument("--target", required=True)
    parser.add_argument("--output-dir", default=str(OUT_DIR))
    parser.add_argument("--strict", action="store_true", help="Return non-zero on HOLD.")
    args = parser.parse_args()

    target = resolve(args.target)
    if not target.exists():
        print(f"Missing target: {target}", file=sys.stderr)
        return 2
    if not target.is_file():
        print(f"Target is not a file: {target}", file=sys.stderr)
        return 2
    text = target.read_text(encoding="utf-8", errors="replace")
    findings = scan(text)
    result = status(findings)

    out_dir = resolve(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report = out_dir / f"Authorial_Voice_Scan_{target.stem}_{datetime.now().strftime('%Y-%m-%d_%H%M%S')}.md"
    report.write_text(render(target, findings), encoding="utf-8")
    append_event(target, report, result)
    print(f"Report: {report}")
    print(f"Status: {result}")
    return 1 if args.strict and result == "HOLD" else 0


if __name__ == "__main__":
    raise SystemExit(main())
