#!/usr/bin/env python3
"""Scan research prose for authorial-voice and generic AI-style risks.

This helper is not an AI detector. It flags workflow risks such as
detector-evasion framing, disclosure hiding, chatbot residue, generic phrasing,
inflated vocabulary, and possible overclaiming.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "audit-reports" / "authorial-voice"
EVENT_LOG = ROOT / "research-wiki" / "SESSION_EVENT_LOG.jsonl"


@dataclass
class Finding:
    severity: str
    category: str
    line: int
    evidence: str
    action: str


PATTERNS: list[tuple[str, str, str, str]] = [
    (
        r"\b(lower|reduce|bypass|evade).{0,45}\b(AI|AIGC|Turnitin|GPTZero|detector|detection).{0,20}\b(rate|score|detector|detection|detectability|flag)\b",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"\b(lower|reduce|bypass|evade).{0,35}\b(AI|AIGC).{0,12}\b(detection|detector)\b",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"(降低|减少|规避|绕过).{0,12}(AI|AIGC|检测|检测率|查重|Turnitin|GPTZero)",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"(降\s*AI|AI\s*率|去\s*AI\s*味|AI\s*痕迹|论文降\s*AI|降低\s*AIGC)",
        "HOLD",
        "detector-evasion framing",
        "Reframe as authorial voice, integrity, and academic style; do not promise detector outcomes.",
    ),
    (
        r"\b(randomi[sz]e|synonym[- ]swap|insert.{0,20}(noise|imperfection)|evade.{0,20}pattern)\b",
        "HOLD",
        "style-evasion tactic",
        "Do not use randomisation, synonym swapping, or deliberate imperfections as an evasion tactic.",
    ),
    (
        r"(随机化|同义词替换|插入噪声|制造不完美|规避模式)",
        "HOLD",
        "style-evasion tactic",
        "Do not use randomisation, synonym swapping, or deliberate imperfections as an evasion tactic.",
    ),
    (
        r"\b(hide|omit|avoid|soften).{0,30}(AI[- ]use|AI disclosure|AI[- ]?use statement|AI statement)\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\b(leave out|don'?t include|do not include|no need to mention).{0,30}\b(AI|AI statement|AI[- ]use|AI disclosure|AI[- ]?use statement)\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\bleave.{0,20}\b(AI|AI statement|AI[- ]use|AI disclosure|AI[- ]?use statement).{0,12}\bout\b",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"(隐藏|省略|不写|不要写|淡化).{0,12}(AI使用|AI声明|AI披露|人工智能使用|披露)",
        "HOLD",
        "AI-use disclosure risk",
        "Do not hide, soften, or invent AI-use disclosure statements.",
    ),
    (
        r"\b(as an ai|as a language model|i am an ai|i'?m an ai|generated by ai)\b",
        "HOLD",
        "prompt or chatbot residue",
        "Remove chatbot meta-text before academic or professional use.",
    ),
    (
        r"\b(it is important to note|it is worth noting|in today'?s.*landscape|rapidly evolving|delve into|shed light on|plays a crucial role)\b",
        "WARN",
        "generic AI-style phrasing",
        "Replace with a direct claim, specific mechanism, or delete the phrase.",
    ),
    (
        r"\b(crucial|pivotal|paramount|multifaceted|nuanced|robust|comprehensive|holistic|seamless|transformative)\b",
        "WARN",
        "inflated or vague academic vocabulary",
        "Quantify, specify, or remove the adjective.",
    ),
    (
        r"\b(furthermore|moreover|additionally)\b",
        "WARN",
        "formulaic transition",
        "Use a transition that states the paragraph's argumentative job.",
    ),
    (
        r"\b(proves|confirms|ensures|eliminates|conclusively demonstrates)\b",
        "WARN",
        "possible overclaim",
        "Check source strength; hedge unless evidence directly supports the certainty.",
    ),
    (
        r"^\s*(This|These|That)\s+(shows|suggests|indicates|means|allows|enables)\b",
        "WARN",
        "weak demonstrative opening",
        "Name the antecedent or rewrite the sentence as a specific mini-claim.",
    ),
]


def resolve(path_text: str) -> Path:
    path = Path(path_text).expanduser()
    return path if path.is_absolute() else ROOT / path


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path.resolve())


def scan(text: str) -> list[Finding]:
    findings: list[Finding] = []
    in_fence = False
    for index, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        quoted_or_fenced = in_fence or stripped.startswith(">")
        for pattern, severity, category, action in PATTERNS:
            if quoted_or_fenced and severity == "WARN":
                continue
            if re.search(pattern, line, flags=re.I):
                findings.append(Finding(severity, category, index, line.strip()[:220], action))
    return findings


def status(findings: list[Finding]) -> str:
    if any(item.severity == "HOLD" for item in findings):
        return "HOLD"
    if findings:
        return "WARN"
    return "PASS"


def render(target: Path, findings: list[Finding]) -> str:
    result = status(findings)
    lines = [
        "# Authorial Voice Scan",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"Target: `{rel(target)}`",
        f"Status: `{result}`",
        "",
        "## Findings",
        "",
        "| Severity | Category | Line | Evidence | Action |",
        "|---|---|---:|---|---|",
    ]
    if findings:
        for item in findings:
            evidence = item.evidence.replace("|", "\\|")
            action = item.action.replace("|", "\\|")
            lines.append(f"| {item.severity} | {item.category} | {item.line} | {evidence} | {action} |")
    else:
        lines.append("| PASS | no finding | - | - | - |")
    lines.extend(
        [
            "",
            "## Boundary",
            "",
            "This scan flags authorial-voice and generic AI-style risks. A `HOLD` result is a workflow warning, not a judgement that text is AI-generated. This scan is not an AI detector, plagiarism detector, source-support check, compliance approval, or official institutional policy.",
            "",
        ]
    )
    return "\n".join(lines)


def append_event(target: Path, report: Path, result: str) -> None:
    EVENT_LOG.parent.mkdir(parents=True, exist_ok=True)
    event = {
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "run_id": f"authorial-voice-scan-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "window": "Production",
        "event_type": "quality_gate",
        "status": "completed",
        "result": result,
        "skill": "authorial-voice-integrity",
        "file": rel(report),
        "evidence": f"Authorial voice scan completed with result {result} for {rel(target)}.",
        "risk": "low" if result == "PASS" else "medium",
    }
    with EVENT_LOG.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(event, ensure_ascii=False) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run an authorial voice and generic AI-style scan.")
    parser.add_argument("--target", required=True)
    parser.add_argument("--output-dir", default=str(OUT_DIR))
    parser.add_argument("--strict", action="store_true", help="Return non-zero on HOLD.")
    parser.add_argument("--write-event", action="store_true", help="Append a local session-event log entry.")
    args = parser.parse_args()

    target = resolve(args.target)
    if not target.exists():
        print(f"Missing target: {target}", file=sys.stderr)
        return 2
    if not target.is_file():
        print(f"Target is not a file: {target}", file=sys.stderr)
        return 2
    text = target.read_text(encoding="utf-8", errors="replace")
    findings = scan(text)
    result = status(findings)

    out_dir = resolve(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report = out_dir / f"Authorial_Voice_Scan_{target.stem}_{datetime.now().strftime('%Y-%m-%d_%H%M%S')}.md"
    report.write_text(render(target, findings), encoding="utf-8")
    if args.write_event:
        append_event(target, report, result)
    print(f"Report: {report}")
    print(f"Status: {result}")
    return 1 if args.strict and result == "HOLD" else 0


if __name__ == "__main__":
    raise SystemExit(main())
